# Generated by Django 6.0.7 on 2026-07-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='rnc',
            field=models.CharField(blank=True, max_length=20, verbose_name='RNC'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
