# Generated by Django 6.0.7 on 2026-07-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracionsitio_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='diseno_recibo',
            field=models.CharField(choices=[('formal', 'Formal (hoja carta)'), ('ticket', 'Ticket térmico (angosto)'), ('minimalista', 'Minimalista')], default='formal', max_length=20),
        ),
    ]
