# Generated by Django 6.0.7 on 2026-07-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='impreso',
            field=models.BooleanField(default=False),
        ),
    ]
