# Generated by Django 6.0.7 on 2026-07-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_backfill_perfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cobrador', 'Cobrador')], default='cobrador', max_length=20),
        ),
    ]
